FROM node:latest
WORKDIR /usr/src/app
COPY ./ ./
RUN npm install
RUN npm run build
ENV NODE_ENV=dev
ENV SESSION_DB_HOST=127.0.0.1
ENV SESSION_DB_PASS=""
ENV SESSION_DB_USER=root
ENV SESSION_DB_PORT=3306
ENV SESSION_DB_DATABASE=demo_dev
ENV MYSQL_HOST=127.0.0.1
ENV MYSQL_PASS=""
ENV MYSQL_USER=root
ENV MYSQL_PORT=3306
ENV MYSQL_DATABASE=demo_test
ENV CORS_ORIGIN="http://localhost:4200"

EXPOSE 3000
CMD [ "npm", "run", "start" ]
